//! UI intent definitions returned by screen renderers.

use crate::state::{EggConversionKind, ExpeditionPriority};

#[derive(Debug, Clone)]
pub enum UiAction {
    StartNewGame,
    ContinueGame,
    ContinueOpening,
    BuildOpeningRoom,
    ResolveOpeningClient,
    QuitGame,
    SaveGame,
    OpenGuildHallManagement,
    OpenContractDesk,
    OpenTownManagement,
    OpenHatcheryManagement,
    OpenJournal,
    OpenExpeditionPlanning,
    OpenMonsterProfile(String),
    SelectContractRequest(String),
    AssignMonsterToGuest(String, String),
    ClearGuestAssignment(String),
    SelectChamberEgg(String),
    ReturnToTownOverview,
    SelectGuildRoom(String),
    SelectTownBuilding(String),
    SelectTownBuildingGroup(String),
    SelectExpeditionFloor(String),
    SelectExpeditionMission(String),
    SetExpeditionPriority(ExpeditionPriority),
    OpenSettings,
    CloseSettings,
    ToggleFullscreen(bool),
    SetResolution(String),
    AssignMonsterToRoom(String, String),
    AssignMonsterToExpedition(String, String),
    AssignMonsterToRest(String),
    AssignMonsterToIdle(String),
    ReleaseMonster(String),
    PurchaseBuilding(String),
    PayDebtNow,
    HatchSelectedEgg(String, Option<String>),
    ReplaceMonsterWithEgg(String, Option<String>, String),
    ConvertEgg(String, EggConversionKind),
    ContinueAfterHatch,
    ResolveDay,
    ContinueAfterResults,
}
